_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 300
learning_rate:
    value: 0.001
